### ISSUE TITLE
Unable to change track for local training

### ISSUE THREAD

**Issue by VanieKimuri** [aws-deepracer-community/deepracer-for-cloud#103]
In the `run.env` file whenever I change the value for `DR_WORLD_NAME` before training, when I upload the model to the aws deepracer console after training it shows the model track to be reinvent_2018 track even when I changed the track to something else.

**Comment by larsll** [comment]
The console does not remember which track you trained on when you upload. (It also does not remember the color of your car...) This is not having anything but cosmetic impact, and is nothing that we can change in DRfC.
