### ISSUE TITLE
Doesn't work with 10.0.0.0/20 CIDR range VPCs

### ISSUE THREAD

**Issue by markrossatos** [aws-deepracer-community/deepracer-for-cloud#113]
Hi,

Thanks for providing this code.  I've discovered that it doesn't work with 10.0.0.0/20 CIDR range, but does with 172.168.0.0/16.  I assume there's something in the configuration caused a clash / overlap.

If not fixed it's definitely worth updating documentation / readmes to avoid others losing many hours of troubleshooting as the behaviour I saw was just that it hung at 'DoorMan: installing SIGINT, SIGTERM' so it wasn't obvious what was going on.

Thanks,

Mark

**Comment by larsll** [comment]
I will incorporate a note in the installation to keep VPC on 172.x.x.x/16 network. I see that mine is on 172.31.0.0/16.

**Comment by larsll** [comment]
It looks like the sagemaker-local docker network is using 10.0.1.0/24. It could be that this causes the collision.

**Comment by larsll** [comment]
The fix in #116 will force new instances to have the sagemaker-local on subnet 192.168.2.0/24; which should prevent this from happening. Document also updated.
