### ISSUE TITLE
dr-update not found

### ISSUE THREAD

**Issue by VPpexis** [aws-deepracer-community/deepracer-for-cloud#119]
Hello, I just got into deepracer and im not really that good.

I tried installing Deepracer-for-cloud on my WSL2 ubuntu distro. Installed all the the prerequisities and tested my cude on my WSL and works. I have also followed the  documentation on installing the DRfC by running this command:
`bin/init.sh -a gpu -c local`

However, when I tried `dr-update` it says that command not found. Hoping someone could help me with this. 
Thank you in advance

**Comment by JabariHolder** [comment]
You need to parse the bin/activate.sh file using `source` (see Local Training Troubleshooting):
https://aws-deepracer-community.github.io/deepracer-for-cloud/installation.html#local-training-troubleshooting

`source bin/activate.sh`

In the event that you do and you get errors. It may be that your shell is outdated. I'd recommend using bash4 or bash5.

For example macOS ships with bash3 so most likely you will need to update, assuming you have brew:
`brew install bash`
