### ISSUE TITLE
Unable to get configuration file

### ISSUE THREAD

**Issue by Won-JoonChoi** [aws-deepracer-community/deepracer-for-cloud#128]
Hello, I recently started Deepracer and I need help with my local environment.

I've installed CUDA toolkit(ver 12.1) and nvidia-docker2, also successfully executed `./bin/init.sh -c local -a gpu`.

After configuring some informations through `aws configure --profile minio`, then I executed `source bin/activate.sh`, the result was `No configuration file.` message.

I've tried a lot to solve this, but couldn't, would appreciate any help.
![image](https://user-images.githubusercontent.com/81273366/226373390-f98853c2-3254-45a2-a3d8-a5c0f24afe01.png)

**Comment by 0styx0** [comment]
@Won-JoonChoi when closing an issue as completed, please include an explanation
