### ISSUE TITLE
nvidia/cuda:11.4.2-base-ubuntu18.04 docker image doesn't exist any more

### ISSUE THREAD

**Issue by heromanba** [aws-deepracer-community/deepracer-for-cloud#138]
Hi, seems nvidia/cuda:11.4.2-base-ubuntu18.04 doesn't exist any more, which caused Dockerfile.gpu-detect to fail even if we have a gpu.
Probably we should instead use nvidia/cuda:11.4.3-base-ubuntu18.04 
 for Dockerfile.gpu-detect ?

thanks!

**Comment by larsll** [comment]
Updated as of https://github.com/aws-deepracer-community/deepracer-for-cloud/commit/dec9e50b931d41d008c008c5fd5e79a918f950b9
