### ISSUE TITLE
-bash: bin/init.sh: No such file or directory

### ISSUE THREAD

**Issue by itserichuang** [aws-deepracer-community/deepracer-for-cloud#141]
When running "bin/init.sh -a gpu -c local" in Ubuntu in Windows 10, it results in "-bash: bin/init.sh: No such file or directory". I'm not sure why this is happening.

**Comment by larsll** [comment]
Are you actually in the `deepracer-for-cloud` directory?

**Comment by itserichuang** [comment]
I'm gonna close this
