### ISSUE TITLE
Sagemaker is not running

### ISSUE THREAD

**Issue by 2112sks** [aws-deepracer-community/deepracer-for-cloud#147]
Sagemaker is not running while local training deepracer aws.i have checked that all docker files are correct and also made docker type swarm.Still it fails to load sagemaker after creating rl coach and robomaker containers.
No other errors are showing other than sagemaker is not running.
![Uploading IMG_20231130_101027.jpg…]()

**Comment by 2112sks** [comment]
![Uploading IMG_20231130_101027.jpg…]()

**Comment by larsll** [comment]
Support is easier to get in our forums - deepracing.io - otherwise update the ticket with log-files; combine `docker ps -a` with a `docker logs <containerid>` to get more details.
