### ISSUE TITLE
DRfC not working in AWS 'opt in' regions

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws-deepracer-community/deepracer-for-cloud#153]
AWS has a list of original regions which are all enabled by default, and then a list of 'opt-in' regions which a user must enable.  Some of these opt-in regions have good prices for spot instances and therefore it's desirable to be able to use them.

It appears that DRFC doesn't work in AWS 'opt in regions', RLCoach image exits: -
![image](https://github.com/aws-deepracer-community/deepracer-for-cloud/assets/53598199/5a3d0460-179d-4036-b9f4-46cc826585ad)

The suggestion from my research is this is because for opt-in regions the region must be specified when making a request, even to S3, and I assume it isn't in the docker containers today, hence above error.

I tested on an Ubuntu linux machine, first request you can see fails, second request with region specified works: -
![image](https://github.com/aws-deepracer-community/deepracer-for-cloud/assets/53598199/4b4bcd7d-040a-4ef5-a91c-9b49b8304a94)

Perhaps this could be solved by adding this to the early part of the docker image when running on AWS, becuase this will set the region and then doesn't require you to set it with each command?: -
export AWS_DEFAULT_REGION=$(curl http://169.254.169.254/latest/meta-data/placement/region)
this would then set the region to the region the instance is running in having queried the metadata service.

**Comment by larsll** [comment]
I tried fixing it the simple way in DRfC's docker file. Can you check if this is sufficient? (`app_region` branch)
The DR_AWS_APP_REGION must be set in system.env

**Comment by MarkRoss-Eviden** [comment]
Reopened.  As discussed Lars dr-download-custom-files doesn't work without the region being set in the terminal.  I imagine other commands that need to interact with the S3 bucket from within the terminal rather than the docker image would also have the same issue.

**Comment by larsll** [comment]
@MarkRoss-Eviden - added the environment variable; could you test now.

**Comment by MarkRoss-Eviden** [comment]
Tested in Milan (one of the opt in regions) with setting DR_AWS_APP_REGION=eu-south-1 in system.env.

Works great so ready to merge @larsll : -

dr-start-training
![image](https://github.com/aws-deepracer-community/deepracer-for-cloud/assets/53598199/95d9e287-5fa4-432d-b72d-12444cad3f26)
