### ISSUE TITLE
The dr-*  S3 Commond unavailable

### ISSUE THREAD

**Issue by LiangweiZhang** [aws-deepracer-community/deepracer-for-cloud#163]
S3 commands cannot be used locally and the following information is displayed，

![image](https://github.com/aws-deepracer-community/deepracer-for-cloud/assets/40728744/7f0ae50d-e24a-4b60-b3b2-9925e3311ea5)

commands ：
1.dr-list-aws-models
2.dr-set-upload-model
3. dr-upload-model
4.dr-download-model

**Comment by larsll** [comment]
For `dr-list-aws-models` and `dr-set-upload-model` this is expected behaviour. The message is programmed into DRfC. `dr-upload-model -i` -- which is the part that uploads into your S3 bucket, and then triggers import into DR console is working as expected.

**Comment by LiangweiZhang** [comment]
How do I view and download models in S3 buckets

> For `dr-list-aws-models` and `dr-set-upload-model` this is expected behaviour. The message is programmed into DRfC. `dr-upload-model -i` -- which is the part that uploads into your S3 bucket, and then triggers import into DR console is working as expected.

**Comment by larsll** [comment]
For support I suggest you join us on Discord: https://join.deepracing.io/

**Comment by LiangweiZhang** [comment]
Thank you. I'm in

> For support I suggest you join us on Discord: https://join.deepracing.io/
