### ISSUE TITLE
Issue when executing activate.sh

### ISSUE THREAD

**Issue by Abhinav1281** [aws-deepracer-community/deepracer-for-cloud#164]
When trying to execute activate.sh in wsl
This line is returned and execution stops
Could not do a RCA for this and any help would be appreciated

>  source bin/activate.Unix.sh
> 
> ) could not be foundminio
> 
> ) could not be foundminio

**Comment by larsll** [comment]
For support I suggest you join us on Discord: https://join.deepracing.io/

**Comment by Abhinav1281** [comment]
Thanks Ill close this ticket then
