### ISSUE TITLE
Intermittent failure to connect to S3 with credentials issue

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws-deepracer-community/deepracer-for-cloud#174]
This issue occurs randomly and has done for a long time (i.e. not been introduced to my knowledge by recent changes to 5.1 or 5.2), and not very often, making it difficult to troubleshoot.  Training works fine for hours (perhaps days), and then  robomaker exits.  

For example this one happened 960 episodes in, you can see it's working and then suddenly it's not.  Instance uses an IAM Instance Profile with full access to S3 (if permissions were an issue it'd fail immediately) : -
![image](https://github.com/aws-deepracer-community/deepracer-for-cloud/assets/53598199/80ed5ba4-3658-4309-98d5-5884ac3ecd03)

Seems this is an issue not limited to DRfC, but is seen by other users doing other things: -
https://github.com/boto/botocore/issues/2117
https://github.com/rom1504/img2dataset/issues/137

There's a suggestion increasing var 'AWS_METADATA_SERVICE_NUM_ATTEMPTS' could work, as we might be getting throttled: -
![image](https://github.com/aws-deepracer-community/deepracer-for-cloud/assets/53598199/f293ce7d-b57f-4630-9bb1-ab6c4230ce22)

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html

**Comment by larsll** [comment]
So two possible workarounds:
- Add normal AWS IAM credentials
- Add the environment variable into `docker/docker-compose-training.yml`

**Comment by MarkRoss-Eviden** [comment]
I'll work on 'Add the environment variable into docker/docker-compose-training.yml' and see what happens, as long as it doesn't introduce new issues it should be safe to merge as adding static creds to instances isn't aws best practice and is actively discourage for security.

**Comment by MarkRoss-Eviden** [comment]
are there any commands in the containers that would be getting the creds specifically, or is it just background stuff the instance is doing?

**Comment by MarkRoss-Eviden** [comment]
should be fixed by https://github.com/aws-deepracer-community/deepracer-for-cloud/pull/175
