### ISSUE TITLE
Line graph problem in the Dashboard

### ISSUE THREAD

**Issue by akiva-skolnik** [aws-deepracer-community/deepracer-for-cloud#185]
The graph is taking into account times without episodes, which cause it to be noisy and hard to interpolate
![image](https://github.com/user-attachments/assets/f38ac565-cc2b-403c-a118-75ede7ba06c4)

**Comment by larsll** [comment]
This is how Grafana works - in most cases the X-axis is a time series. You are naturally free to configure Grafana however you like, it is only a sample dashboard provided.
