### ISSUE TITLE
'sh: 1: !!: not found' showing in log output terminal

### ISSUE THREAD

**Issue by Acedportugas** [aws-deepracer-community/deepracer-for-cloud#48]
Hi, 
This is my first time doing this and i am not a advanced linux user.I noticed that when i run ./start.sh the following error message is shown in the terminal where the log output is to shown.  **'sh: 1: !!: not found'**. I also noticed that i dont have the sagemaker folder in docker/volumes/minio/bucket.

**Comment by larsll** [comment]
Please try to re-install. Deepracer-for-Dummies was out of date.
