### ISSUE TITLE
Sagemaker frozen after printing "Checkpoint> Saving in path=['./checkpoint/agent/0_Step-0.ckpt']"

### ISSUE THREAD

**Issue by yifan-w** [aws-deepracer-community/deepracer-for-cloud#53]
Hi there. I'm running on Ubuntu 18.04 with an Nvidia Tesla P4 gpu. I've managed to get the containers running for dr-start-training with default configs and local mode. However the log froze after printing this message:
> Checkpoint> Saving in path=['./checkpoint/agent/0_Step-0.ckpt']

I checked the checkpoint path and all the files were not changed at all (neither size nor modified time), while the cpu remains at 100% consumption by the python process. 

I've located the source of this log message to line 61 of **training_worker.py**
```python
# save initial checkpoint                                           
graph_manager.save_checkpoint()
```
but couldn't debug further from there.

Any idea what could be causing this problem?

Thanks

**Comment by larsll** [comment]
@yifan-w - for general support I would suggest to head over to deepracing.io and the Slack community.

**Comment by yifan-w** [comment]
> @yifan-w - for general support I would suggest to head over to deepracing.io and the Slack community.

Got it. Thanks.

**Comment by yifan-w** [comment]
> @yifan-w - for general support I would suggest to head over to deepracing.io and the Slack community.

Got it. Thanks.
