### ISSUE TITLE
dr-download-model error when downloading from default S3 export path

### ISSUE THREAD

**Issue by yyao84** [aws-deepracer-community/deepracer-for-cloud#74]
The default export path from the DeepRacer console is:
`s3://aws-deepracer-assets-<uid>/<model>/<timestamp>/`,
where timestamp is in the format `%a, %d %b %Y %H:%M:%S %Z` e.g. `Wed, 27 Oct 2021 19:42:10 GMT`

`dr-download-model` doesn't preserve the `-s source-url` string all the way through the script, so the aws s3 sync command fails.

**Comment by larsll** [comment]
@yyao84  - please confirm if this now works on master branch.
