### ISSUE TITLE
minio GUI disabled by default in system.env

### ISSUE THREAD

**Issue by gitobic** [aws-deepracer-community/deepracer-for-cloud#77]
Did a fresh / clean install using all new pulls.  MinIO gui on port 9000 will not authenticate.  The profile is set and the login page loads, but rejects all authentication attempts.

The setting of
`DR_GUI_ENABLE=False`
in the default system.env is the culprit.  Setting it to 
`DR_GUI_ENABLE=True`
enables MinIO to authenticate at login

Suggested fixes:

- Additional documentation to call this setting out
- Update creation of system.env to set it to True

**Comment by larsll** [comment]
Can you provide any logs around this? DR_GUI_ENABLE is only passed into the robomaker container, and should not be relevant for minio at all.

**Comment by larsll** [comment]
@gitobic - any further input?

**Comment by larsll** [comment]
Closing due to no feedback.
