### ISSUE TITLE
Unable to find deepracer checkpoint json

### ISSUE THREAD

**Issue by dawiddzhafarov** [aws-deepracer-community/deepracer-for-cloud#87]
Hello, while trying to start training default model, after whole configuration, when I run dr-start-training, this is the place where it all gets stuck. No idea what to do, would appreciate any help
![error](https://user-images.githubusercontent.com/56120592/164489953-6c2167bd-ef89-48a6-b086-5c3b6c133116.png)

**Comment by Lacan82** [comment]
This is normal for when you start a new training. If you are starting a pre-trained then this isn't normal. Working as intended otherwise,

**Comment by dawiddzhafarov** [comment]
So how do I know that the training has started? Nothing else shows up, no information about the training.

**Comment by Lacan82** [comment]
You need to wait and give Doorman time to finish installing SIGINIT and SIGTERM. Once it starts you'll see data flow across the screen for the training and policy updates

**Comment by dawiddzhafarov** [comment]
Okay, thanks for the answer. Last time I have waited about an hour and nothing happened, but I will give it a go.
