### ISSUE TITLE
Default hyperparameters

### ISSUE THREAD

**Issue by rohand2412** [aws-deepracer-community/deepracer-for-cloud#97]
This isn't a bug or issue actually, but rather a question.

This is the DRfC default hyperparameters.json

    {
        "batch_size": 64,
        "beta_entropy": 0.01,
        "discount_factor": 0.995,
        "e_greedy_value": 0.05,
        "epsilon_steps": 10000,
        "exploration_type": "categorical",
        "loss_type": "huber",
        "lr": 0.0003,
        "num_episodes_between_training": 20,
        "num_epochs": 10,
        "stack_size": 1,
        "term_cond_avg_score": 350.0,
        "term_cond_max_episodes": 1000,
        "sac_alpha": 0.2
    }

I was wondering how you came up with values for the `e_greedy_value`, `epsilon_steps`, `exploration_type`, `stack_size`, `term_cond_avg_score`, `term_cond_max_episodes`, and `sac_alpha`? Or where I can find the AWS Deepracer official defaults for these values? I found defaults on the AWS DeepRacer documentation for the other values.

Thanks

**Comment by larsll** [comment]
The defaults normally come out of the values provided by AWS. If you download the logs from the console you will see.

**Comment by rohand2412** [comment]
Okay I'll do that thanks!
